# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: ported - Software developer
author: ported
description: >- # this means to ignore newlines until "baseurl:"
  Software developer documenting things I couldn't find a solution to and proceeded to find out myself
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://ported.pw" # the base hostname & protocol for your site, e.g. http://example.com

avatar: https://avatars3.githubusercontent.com/u/34283054?s=460&v=4

navbar-links:
  About Me: "about"

social-network-links:
  github: ported-pw
  email: contact@ported.pw

url-pretty: ported.pw

# Whether or not to show an excerpt for every blog post in the feed page
feed_show_excerpt: true

# Whether or not to show a list of tags below each post preview in the feed page
feed_show_tags: true

# Add a search button to the navbar
post_search: true

# Add a button in the footer to edit the current page. Only works if your website is hosted on GitHub
edit_page_button: true

disqus: ported-pw

# Output options (more information on Jekyll's site)
timezone: "Europe/Berlin"

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
      social-share: true # add social media sharing buttons to all blog posts
  -
    scope:
      path: "" # any file that's not a post will be a "page" layout by default
    values:
      layout: "page"

# Build settings
markdown: kramdown
remote_theme: daattali/beautiful-jekyll@5.0.0
plugins:
  - jekyll-paginate
  - jekyll-sitemap

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
